version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - PG_HOST=postgresql
      - PG_PORT=5432
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: root

