---
name: CI/CD Pipeline with DockerHub and JFrog

'on':
  push:
    branches:
      - main

jobs:
  sonarcloud-and-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"

      # Step 3: Run SonarCloud Analysis
      - name: SonarCloud Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=java-mysql-pgsql \
            -Dsonar.organization=lskengineer \
            -Dsonar.branch.name=main \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Step 4: Download Artifact from JFrog
      - name: Download Artifact from JFrog
        run: |
          curl -fL https://getcli.jfrog.io | sh
          ./jfrog config add my-jfrog-server \
            --artifactory-url=${{ secrets.JFROG_URL }} \
            --user=${{ secrets.JFROG_USERNAME }} \
            --password=${{ secrets.JFROG_PASSWORD }}
          ./jfrog rt dl \
            "libs-release-local/java-mysql-pgsql/*.jar" \
            ./artifact.jar --server-id=my-jfrog-server

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/java-mysql-pgsql:latest \
            --build-arg ARTIFACT=./artifact.jar .

      # Step 6: Log in to DockerHub
      - name: Log in to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | \
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 7: Push Docker Image to DockerHub
      - name: Push Docker Image
        run: docker push your-dockerhub-username/java-mysql-pgsql:latest
