---
name: SonarCloud Analysis

'on':
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"

      # Step 3: Run SonarCloud Analysis
      - name: SonarCloud Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=java-mysql-pgsql \
            -Dsonar.organization=lskengineer \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
