name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Debug - List target files
      - name: Debug: List target files
        run: ls -la target

      # Step 5: Test JFrog CLI
      - name: Test JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          ./jfrog config add my-jfrog-server \
            --artifactory-url=${{ secrets.JFROG_URL }} \
            --user=${{ secrets.JFROG_USERNAME }} \
            --password=${{ secrets.JFROG_PASSWORD }}
          ./jfrog rt ping --server-id=my-jfrog-server

      # Step 6: Upload Artifact to JFrog
      - name: Upload Artifact to JFrog
        run: |
          ARTIFACT_NAME=$(ls target/*.jar)
          ./jfrog rt u "$ARTIFACT_NAME" "libs-release-local/java-mysql-pgsql/${ARTIFACT_NAME##*/}" \
            --server-id=my-jfrog-server
