name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (Ensure Java 17 is used)
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Debug - Verify Java version
      - name: Verify Java Version
        run: java -version

      # Step 4: Debug - Check Git Branch
      - name: Debug: Check Git Branch
        run: git branch -a

      # Step 5: Perform SonarCloud Analysis
      - name: SonarCloud Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=java-mysql-pgsql \
            -Dsonar.organization=lskengineer \
            -Dsonar.branch.name=main \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

